---
- hosts: galaxyservers
  become: true
  # become_user: root
  vars_files:             
    - group_vars/secret.yml

  pre_tasks:
    - name: Include tasks for CentOS7
      import_tasks: pre_task_centos.yml
      when: ansible_distribution == 'CentOS'

    - name: Include tasks for RockyLinux9
      import_tasks: pre_task_RockyLinux.yml
      when: ansible_distribution == "Rocky"

    - name: Update ca-certificates
      yum:
        name: ca-certificates
        state: latest

  roles:
    - role: galaxyproject.postgresql
    - role: galaxyproject.postgresql_objects
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - galaxyproject.miniconda
    - usegalaxy_eu.certbot
    - galaxyproject.nginx
    - galaxyproject.tusd
