- hosts: pulsarservers
  vars_files:
    - group_vars/secret.yml
  pre_tasks:

    - name: Include tasks for RockyLinux9
      import_tasks: pre_task_RockyLinux.yml
      when: ansible_distribution == "Rocky"

  roles:
    - role: galaxyproject.cvmfs
      become: yes
    - galaxyproject.pulsar
